
HA=[[HistoriedAccuracy.allcat]; [HistoriedAccuracy.cat]; ...
    [HistoriedAccuracy.dom]; [HistoriedAccuracy.etd]; ...
    [HistoriedAccuracy.ed]; [HistoriedAccuracy.morph]; ...
    [HistoriedAccuracy.num]; [HistoriedAccuracy.tec]; ...
    [HistoriedAccuracy.last]; ...
    [HistoriedAccuracy.median]; ...
    [HistoriedAccuracy.mode]; ...
    [HistoriedAccuracy.min]; ...
    [HistoriedAccuracy.max]];

HN=[[HistoriedNumbers.allcat]; [HistoriedNumbers.cat]; ...
    [HistoriedNumbers.dom]; [HistoriedNumbers.etd]; ...
    [HistoriedNumbers.ed]; [HistoriedNumbers.morph]; ...
    [HistoriedNumbers.num]; [HistoriedNumbers.tec]
    [HistoriedNumbers.Simple]; [HistoriedNumbers.Simple]; ...
    [HistoriedNumbers.Simple]; [HistoriedNumbers.Simple]; ...
    [HistoriedNumbers.Simple]];

h=bar(HA);
l=legend([Result(:,1,:,1).VolcanoDatasetName]);
%x=[{'All Categories'},{'Tectonic Setting'},{'Dominant Rock Type'},{'Morphology'}];
Attributes = {'All Attributes','Categorical Data','Dominant Rock Type', ...
    'Repose Time','Eruption Duration','Morphology','All Numerical Data','Tectonic Setting' ...
    'Last VEI','Median VEI','Mode VEI','Min VEI','Max VEI'};

set(gca,'XTickLabel',Attributes)

for ih=1:length(h),
     text(h(ih).XEndPoints,h(ih).YData,num2cell(HN(:,ih)), ...
        'HorizontalAlignment','right','VerticalAlignment','middle', ...
        'Color', 'w', 'Rotation', 90,'Fontsize',12)
end
%'HorizontalAlignment','right','VerticalAlignment','middle', 'Color', 'w', 'Rotation', 90,'Fontsize',11)
ylabel('Total Accuracy ')
ylim([0 1])
% separate simple predictors

line(([1 1]*h(5).XEndPoints(8)+h(1).XEndPoints(9))/2,[0 1], ...
    'Color','k','LineStyle','--')
legend(l.String{1:5});
